---
- name: Restart ssh
  become: true
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Restart fail2ban
  become: true
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Restart journald
  become: true
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
