description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 10
    - uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: '20'
    - run: |
        pnpm install --no-frozen-lockfile
        pnpm prisma generate
        # Rebuild bcrypt to ensure native modules are properly compiled
        pnpm rebuild bcrypt
      shell: bash
  using: composite
