description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: '22'
    - run: |
        pnpm install --no-frozen-lockfile
        pnpm prisma generate
      shell: bash
  using: composite
