name: Test
on:
  pull_request: ~
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: 'Asia/Tokyo'
      - uses: actions/checkout@v7
      - uses: ./.github/actions/prepare
      - name: Create .env file for tests
        run: cp .env.test .env
      - name: Install Playwright browsers
        run: pnpm exec playwright install
      - name: Test
        run: pnpm test
